import { test, expect } from '@playwright/test';

test('agregar un nuevo comercio', async ({ page }) => {
  await page.goto('http://localhost:3001/');
  await page.getByRole('link', { name: 'Registrarse' }).click();
  await page.getByText('🏪 Comercio').click();
  await page.getByRole('textbox', { name: 'Nombre *' }).click();
  await page.getByRole('textbox', { name: 'Nombre *' }).fill('gabriela');
  await page.getByRole('textbox', { name: 'Apellido *' }).click();
  await page.getByRole('textbox', { name: 'Apellido *' }).fill('mayta');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('gabrielaa@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email *' }).fill('gabrielaa@gmail.comT');
  await page.getByRole('textbox', { name: 'Email *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email *' }).fill('gabrielaa@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).fill('T');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).fill('Test123!');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).click();
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).fill('T');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).fill('Test123!1');
  await page.getByRole('textbox', { name: 'Teléfono *' }).click();
  await page.getByRole('textbox', { name: 'Teléfono *' }).fill('1');
  await page.getByRole('textbox', { name: 'Teléfono *' }).click();
  await page.getByRole('textbox', { name: 'Teléfono *' }).fill('1232123233');
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).click();
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).fill('A');
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).fill('Almacen');
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Almacén' }).click();
  await page.getByRole('textbox', { name: 'Dirección del Local *' }).click();
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).click();
  await page.getByRole('textbox', { name: 'Nombre del Comercio *' }).fill('Almacen 1234');
  await page.getByRole('textbox', { name: 'Dirección del Local *' }).click();
  await page.getByRole('textbox', { name: 'Dirección del Local *' }).fill('ordoñez 2324');
  await page.getByRole('textbox', { name: 'Descripción del Comercio' }).click();
  await page.getByRole('textbox', { name: 'Descripción del Comercio' }).fill('holaa');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Completar Registro' }).click();
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).dblclick();
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).fill('T');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).fill('Test123!');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).dblclick();
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).fill('T');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).fill('Test123!');
  await page.getByRole('button', { name: 'Completar Registro' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.goto('http://localhost:3001/');
  await expect(page.getByRole('heading', { name: 'Almacen 1234' })).toBeVisible();
});