import { test, expect } from '@playwright/test';


test('test', async ({ page }) => {
 await page.goto('http://localhost:3000/');
 await page.getByRole('link', { name: 'Registrarse' }).click();
 await page.getByText('🔧 Profesional').click();
 await page.getByRole('textbox', { name: 'Nombre *' }).click();
 await page.getByRole('textbox', { name: 'Nombre *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Nombre *' }).fill('L');
 await page.getByRole('textbox', { name: 'Nombre *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Nombre *' }).fill('Lucia');
 await page.getByRole('textbox', { name: 'Apellido *' }).click();
 await page.getByRole('textbox', { name: 'Apellido *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Apellido *' }).fill('M');
 await page.getByRole('textbox', { name: 'Apellido *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Apellido *' }).fill('Mendez');
 await page.getByRole('textbox', { name: 'Email *' }).click();
 await page.getByRole('textbox', { name: 'Email *' }).fill('luciaa@gmail.com');
 await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).click();
 await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).fill('T');
 await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Contraseña *', exact: true }).fill('Test1234_');
 await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).click();
 await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).fill('T');
 await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Confirmar Contraseña *' }).fill('Test1234_');
 await page.getByRole('textbox', { name: 'Teléfono *' }).click();
 await page.getByRole('textbox', { name: 'Teléfono *' }).fill('1134354545');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).click();
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).fill('M');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).fill('Manicuria ');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).fill('Manicuria L');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Nombre del Servicio *' }).fill('Manicuria Luci');
 await page.getByRole('combobox').click();
 await page.getByRole('option', { name: 'Belleza' }).click();
 await page.getByRole('textbox', { name: 'Años de Experiencia *' }).click();
 await page.getByRole('textbox', { name: 'Años de Experiencia *' }).fill('3');
 await page.getByRole('textbox', { name: 'Zona de Cobertura *' }).click();
 await page.getByRole('textbox', { name: 'Zona de Cobertura *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Zona de Cobertura *' }).fill('L');
 await page.getByRole('textbox', { name: 'Zona de Cobertura *' }).press('CapsLock');
 await page.getByRole('textbox', { name: 'Zona de Cobertura *' }).fill('Lugano 1y2');
 await page.getByRole('textbox', { name: 'Descripción de tus Servicios' }).click();
 await page.getByRole('textbox', { name: 'Descripción de tus Servicios' }).fill('holaa');
 await page.getByRole('textbox', { name: 'Disponibilidad (opcional)' }).click();
 await page.getByRole('textbox', { name: 'Disponibilidad (opcional)' }).fill('lunes a viernes 9-17');
 await page.getByRole('button', { name: 'Completar Registro' }).click();
 await page.goto('http://localhost:3000/');
 await page.getByText('Manicuria Luci').click();
   await expect(page.getByRole('heading', { name: 'Manicuria Luci' })).toBeVisible();

});
